#!/bin/bash

VERSION=0.0.1
TAGNAME=

# Generated by getoptions (BEGIN)
# URL: https://github.com/ko1nksm/getoptions (v3.3.0)
TITLE=''
RATIO=''
LANG=''
COLOR=''
ANCHORS=''
REST=''
parse() {
  OPTIND=$(($#+1))
  while OPTARG= && [ $# -gt 0 ]; do
    case $1 in
      --?*=*) OPTARG=$1; shift
        eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
        ;;
      --no-*|--without-*) unset OPTARG ;;
      -[trlc]?*) OPTARG=$1; shift
        eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
        ;;
      -[avh]?*) OPTARG=$1; shift
        eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
        OPTARG= ;;
    esac
    case $1 in
      '-t'|'--title')
        [ $# -le 1 ] && set "required" "$1" && break
        OPTARG=$2
        TITLE="$OPTARG"
        shift ;;
      '-r'|'--ratio')
        [ $# -le 1 ] && set "required" "$1" && break
        OPTARG=$2
        RATIO="$OPTARG"
        shift ;;
      '-l'|'--lang')
        [ $# -le 1 ] && set "required" "$1" && break
        OPTARG=$2
        LANG="$OPTARG"
        shift ;;
      '-c'|'--color')
        [ $# -le 1 ] && set "required" "$1" && break
        OPTARG=$2
        COLOR="$OPTARG"
        shift ;;
      '-a'|'--anchors')
        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
        ANCHORS="$OPTARG"
        ;;
      '-v'|'--version')
        echo "${VERSION}"
        exit 0 ;;
      '-h'|'--help')
        usage
        exit 0 ;;
      --)
        shift
        while [ $# -gt 0 ]; do
          REST="${REST} \"\${$(($OPTIND-$#))}\""
          shift
        done
        break ;;
      [-]?*) set "unknown" "$1"; break ;;
      *)
        REST="${REST} \"\${$(($OPTIND-$#))}\""
    esac
    shift
  done
  [ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }
  case $1 in
    unknown) set "Unrecognized option: $2" "$@" ;;
    noarg) set "Does not allow an argument: $2" "$@" ;;
    required) set "Requires an argument: $2" "$@" ;;
    pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
    notcmd) set "Not a command: $2" "$@" ;;
    *) set "Validation error ($1): $2" "$@"
  esac
  echo "$1" >&2
  exit 1
}
usage() {
cat<<'GETOPTIONSHERE'
Usage: md2pdf [options] [infile]

Options:
  -t, --title TITLE           title
  -r, --ratio RATIO           image ratio in percent
  -l, --lang LANG             language spec
  -c, --color COLOR           color spec
  -a, --anchors               show anchor ids and texts of headings
  -v, --version               show version
  -h, --help                  display help for command
GETOPTIONSHERE
}
# Generated by getoptions (END)

parse "$@"
eval "set -- $REST"

if [ $# -gt 1 ]; then
  echo >&2 'Error: too many input files'
  exit 1
elif [ $# -eq 1 -a "$1" = '-' -o $# -eq 0 ]; then
  DIRNAME=$PWD
  INFILE=-
else
  DIRNAME=$(cd `dirname "$1"` 2>/dev/null; echo $PWD)
  INFILE=$(basename "$1")
fi

OPTS=(${TITLE:+-t "$TITLE"} ${RATIO:+-r "$RATIO"})
OPTS+=(${LANG:+-l "$LANG"} ${COLOR:+-c "$COLOR"} ${ANCHORS:+-a} -b /opt/app/mnt)

MOUNT=(-v "$DIRNAME:/opt/app/mnt")
IMAGE="md2pdf${TAGNAME:+:$TAGNAME}"

docker run --rm -i "${MOUNT[@]}" "$IMAGE" node md2pdf.js "${OPTS[@]}" "$INFILE"
